services:
  open-webui:
    image: ghcr.io/openwebui/openwebui:latest
    container_name: open-webui
    ports:
      - "3000:3000"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      ENABLE_RAG_WEB_SEARCH: "true"
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
      ENABLE_WEBSOCKET_SUPPORT: "true"
      WEBSOCKET_MANAGER: "redis"
      WEBSOCKET_REDIS_URL: "redis://redis:6379/1"
    networks:
      - openwebui-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      com.example.service: "open-webui"
      com.example.version: "1.0"
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - searxng-data:/etc/searxng
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - openwebui-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      com.example.service: "searxng"
      com.example.version: "1.0"
    restart: unless-stopped

  redis:
    image: docker.io/valkey/valkey:8.0.1-alpine
    container_name: redis-valkey
    volumes:
      - redis-data:/data
    command: "valkey-server --save 30 1"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      interval: 10s
      timeout: 3s
      retries: 5
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - openwebui-network
    labels:
      com.example.service: "redis"
      com.example.version: "1.0"
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    volumes:
      - pipelines-data:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - openwebui-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9099 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      com.example.service: "pipelines"
      com.example.version: "1.0"
    restart: always

  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    volumes:
      - tika-data:/data
    networks:
      - openwebui-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9998 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      com.example.service: "tika"
      com.example.version: "1.0"
    restart: unless-stopped

volumes:
  open-webui-data:
  searxng-data:
  redis-data:
  pipelines-data:
  tika-data:

networks:
  openwebui-network:
    external: true
